# Generated by Django 5.2.1 on 2025-06-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_media_options_media_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image_data',
        ),
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
