# Generated by Django 5.2.1 on 2025-06-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_media_image_data_media_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-is_primary', '-created_at'], 'verbose_name_plural': 'Media'},
        ),
        migrations.RemoveField(
            model_name='media',
            name='content_type',
        ),
        migrations.AddField(
            model_name='media',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Imagem principal do produto'),
        ),
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnails/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload de imagens (JPEG, PNG, WEBP)', null=True, upload_to='products/images/%Y/%m/%d/'),
        ),
    ]
