# Generated by Django 5.1.7 on 2025-03-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_remove_character_image_type_character_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='accessories',
            field=models.CharField(choices=[('', 'No selection'), ('WW_SG', 'Wristwatch and Sunglasses'), ('HT_SG', 'Hat and Sunglasses'), ('BR_WW', 'Bracelet and Wristwatch'), ('EA_RNG', 'Earrings and Ring'), ('WW_HT', 'Wristwatch and Hat'), ('SC_WW', 'Scarf and Wristwatch'), ('SG_BG', 'Sunglasses and Bag'), ('TP_BU', 'Tie and Belt'), ('BR_SC', 'Bracelet and Scarf'), ('NC_WW', 'Necklace and Wristwatch'), ('WW_EA', 'Wristwatch and Earrings'), ('SG_EA', 'Sunglasses and Earrings'), ('WW_BA', 'Wristwatch and Bracelet')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='camera',
            field=models.CharField(choices=[('', 'No selection'), ('CANON_XTi', 'Canon EOS Digital Rebel XTi'), ('NIKON_D810', 'Nikon D810'), ('CANON_1000D', 'Canon EOS 1000D')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='clothing',
            field=models.CharField(choices=[('', 'No selection'), ('LB_SJ_DJ', 'Light Blue Shirt and Dark Jeans'), ('WB_SJ_LJ', 'White Button-up Shirt and Light Jeans'), ('BL_SJ_DJ', 'Black Shirt and Dark Jeans'), ('GR_T_SH_LJ', 'Gray T-shirt and Light Jeans'), ('RD_SJ_BJ', 'Red Shirt and Black Jeans'), ('BL_T_SH_DJ', 'Blue T-shirt and Dark Jeans'), ('GR_HO_LJ', 'Gray Hoodie and Light Jeans'), ('BL_HO_DJ', 'Black Hoodie and Dark Jeans'), ('WH_DRS_LJ', 'White Dress and Light Jeans'), ('FL_JKT_DJ', 'Flannel Jacket and Dark Jeans'), ('WI_T_SH_LJ', 'White T-shirt and Light Jeans'), ('GR_HO_BJ', 'Gray Hoodie and Black Jeans'), ('NV_SJ_LJ', 'Navy Shirt and Light Jeans'), ('BL_CJ_BJ', 'Black Cardigan and Black Jeans'), ('RD_T_SH_LJ', 'Red T-shirt and Light Jeans')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='clothing_style',
            field=models.CharField(choices=[('', 'No selection'), ('CA', 'Casual'), ('FO', 'Formal'), ('SP', 'Sporty'), ('BU', 'Business'), ('ST', 'Streetwear'), ('BO', 'Bohemian'), ('GO', 'Gothic'), ('VI', 'Vintage'), ('PU', 'Punk'), ('EL', 'Elegant')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='ethnicity',
            field=models.CharField(choices=[('', 'No selection'), ('WH', 'White'), ('BL', 'Black'), ('LA', 'Latino/Hispanic'), ('EA', 'East Asian'), ('SA', 'South Asian'), ('ME', 'Middle Eastern'), ('IN', 'Indigenous')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='exposure',
            field=models.CharField(choices=[('', 'No selection'), ('1_160', '1/160'), ('1_5', '1/5'), ('1_800', '1/800')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='expression',
            field=models.CharField(choices=[('', 'No selection'), ('CF', 'Confident'), ('SM', 'Smiling'), ('SO', 'Serious'), ('AN', 'Angry'), ('SA', 'Sad'), ('NE', 'Neutral'), ('FR', 'Frightened'), ('EX', 'Excited'), ('SU', 'Surprised'), ('DI', 'Disappointed')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='eye_color',
            field=models.CharField(choices=[('', 'No selection'), ('BR', 'Brown'), ('BL', 'Blue'), ('GR', 'Green'), ('HA', 'Hazel'), ('AM', 'Amber'), ('GY', 'Gray'), ('VI', 'Violet')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('', 'No selection'), ('M', 'Male'), ('F', 'Female')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair_color',
            field=models.CharField(choices=[('', 'No selection'), ('BK', 'Black'), ('BR', 'Brown'), ('BL', 'Blonde'), ('RD', 'Red'), ('GY', 'Gray'), ('WH', 'White'), ('AU', 'Auburn'), ('BU', 'Blue'), ('GR', 'Green'), ('PU', 'Purple'), ('PI', 'Pink'), ('SI', 'Silver')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair_style',
            field=models.CharField(choices=[('', 'No selection'), ('SH_WG', 'Short and Well-Groomed'), ('SH_UN', 'Short and Unkempt'), ('MD_WG', 'Medium and Well-Groomed'), ('MD_UN', 'Medium and Unkempt'), ('LN_WG', 'Long and Well-Groomed'), ('LN_UN', 'Long and Unkempt'), ('CU_WG', 'Curly and Well-Groomed'), ('CU_UN', 'Curly and Unkempt'), ('ST_WG', 'Straight and Well-Groomed'), ('ST_UN', 'Straight and Unkempt'), ('WI_WG', 'Wavy and Well-Groomed'), ('WI_UN', 'Wavy and Unkempt'), ('BU_WG', 'Buzz Cut and Well-Groomed'), ('BU_UN', 'Buzz Cut and Unkempt'), ('AF_WG', 'Afro and Well-Groomed'), ('AF_UN', 'Afro and Unkempt'), ('MO_WG', 'Mullet and Well-Groomed'), ('MO_UN', 'Mullet and Unkempt')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='image_additional_details',
            field=models.CharField(choices=[('', 'No selection'), ('NB_UR', 'No Background, Ultra-realistic'), ('BG_NM', 'Background, Night Mode'), ('BG_SF', 'Background, Soft Focus'), ('NB_DR', 'No Background, Dramatic Lighting'), ('BG_HD', 'Background, High Definition'), ('NB_LD', 'No Background, Low Detail'), ('BG_VS', 'Background, Vintage Style'), ('NB_PS', 'No Background, Pseudo-realistic'), ('BG_SV', 'Background, Sepia Vibe'), ('NB_SF', 'No Background, Soft Focus'), ('BG_CE', 'Background, Cinematic Effect')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='image_contrast',
            field=models.CharField(choices=[('', 'No selection'), ('VH', 'Very High'), ('HI', 'High'), ('MD', 'Moderate'), ('LO', 'Low'), ('VL', 'Very Low'), ('NO', 'None')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='image_dominant_colors',
            field=models.CharField(choices=[('', 'No selection'), ('NE', 'Neutral'), ('RD', 'Red'), ('BL', 'Blue'), ('GR', 'Green'), ('YL', 'Yellow'), ('OR', 'Orange'), ('PK', 'Pink'), ('WT', 'White'), ('BK', 'Black'), ('GRD', 'Gradient'), ('VIO', 'Violet'), ('BRN', 'Brown'), ('BE', 'Beige'), ('CR', 'Cream'), ('IV', 'Ivory')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='image_lighting',
            field=models.CharField(choices=[('', 'No selection'), ('SD', 'Soft and Diffuse'), ('HR', 'Harsh'), ('DR', 'Dramatic'), ('NT', 'Natural'), ('BC', 'Backlit'), ('CL', 'Cinematic'), ('MG', 'Moody and Gloomy'), ('GD', 'Golden Hour'), ('BL', 'Blue Hour'), ('NE', 'Neon Glow')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='image_shading',
            field=models.CharField(choices=[('', 'No selection'), ('SO', 'Soft'), ('MO', 'Moderate'), ('HR', 'Harsh'), ('DR', 'Dramatic'), ('NO', 'None')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='image_style',
            field=models.CharField(choices=[('', 'No selection'), ('RL', 'Photorealistic'), ('CT', 'Cartoon'), ('AB', 'Abstract'), ('PA', 'Painting'), ('3D', '3D Render'), ('AN', 'Anime'), ('SK', 'Sketch'), ('CG', 'Concept Art'), ('IM', 'Illustration'), ('SG', 'Studio Ghibli'), ('DS', 'Disney Animation'), ('PX', 'Pixar'), ('WB', 'Warner Bros Animation')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='image_texture',
            field=models.CharField(choices=[('', 'No selection'), ('SM', 'Smooth'), ('RF', 'Rough'), ('GR', 'Grainy')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='iso',
            field=models.CharField(choices=[('', 'No selection'), ('ISO_64', 'ISO 64'), ('ISO_200', 'ISO 200'), ('ISO_400', 'ISO 400')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='lens',
            field=models.CharField(choices=[('', 'No selection'), ('100_300mm_f5_6', '100-300mm Canon f/5.6'), ('18mm_f3_5', '18mm Canon f/3.5'), ('85mm_f2_5', '85mm f/2.5')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='pose',
            field=models.CharField(choices=[('', 'No selection'), ('FF_UP', 'Facing Forward, Upright Posture'), ('FF_SL', 'Facing Forward, Slight Lean'), ('SI', 'Sitting'), ('ST', 'Standing'), ('ST_RL', 'Standing, Relaxed'), ('ST_HS', 'Standing, Hands in Pockets'), ('LF', 'Leaning Forward'), ('BF', 'Bent Forward'), ('LS', 'Leaning Sideways'), ('RF', 'Reclining Forward'), ('BF_AR', 'Bent Forward, Arms Resting'), ('TF', 'Tightened Frame, Body Forward')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='skin',
            field=models.CharField(choices=[('', 'No selection'), ('LT', 'Light'), ('MD', 'Medium'), ('DR', 'Dark'), ('VL', 'Very Light'), ('VD', 'Very Dark'), ('OL', 'Olive')], default='', max_length=10),
        ),
    ]
